on: 
  workflow_dispatch:
  push:
    branches: 
      - 'master'
    tags: 
      - 'v*'
  pull_request: 
    branches: 
      - 'master'

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: dockerMetaData
        id: meta
        uses: docker/metadata-action@v5
        with:
        images: w267bxh/project4
      - name: Docker-Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    
