on:
  push

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
    - name: Get-Updates
      run: sudo apt update
    - name: Install-Docker
      run: sudo apt install docker
    - name: Install-Dependencies
      run: sudo apt install podman
    - name: Checkout
      uses: docker/build-push-action@v1
      with: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: WSU-kduncan/f23cicd-benXhawk
        tags: latest, ${{ github.run_number }}

    - name: Push Container
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: w267bxh/project4
        tags: latest, ${{ github.run_number }}
